del /q /s *.dcu
del /q /s *.exe
del /q /s *.dll
del /q /s *.dof
del /q /s *.cbk
del /q /s *.drc
del /q /s *.dsk
del /q /s *.dsm
del /q /s *.rsm
del /q /s *.identcache
del /q /s *.local
del /q /s *.map
del /q /s *.otares
del /q /s *.stat
rmdir /Q /S Source\__history
rmdir /Q /S Packages\__history
rmdir /Q /S Library\D2010
rmdir /Q /S "Library\Delphi 6"
rmdir /Q /S Library\DXE4
rmdir /Q /S Library\DXE5
rmdir /Q /S Library\DXE6
rmdir /Q /S Library\DXE7
rmdir /Q /S Library\DXE8
rmdir /Q /S Library\DX10S
rmdir /Q /S Library\DX101B
rmdir /Q /S Library\DX102T
rmdir /Q /S Library\DX103R

rmdir /Q /S "Demos\Adapters\__history"
rmdir /Q /S "Demos\AsyncSource\__history"
rmdir /Q /S "Demos\AsyncSource with Filestreams\__history"
rmdir /Q /S "Demos\AsyncTarget\__history"
rmdir /Q /S "Demos\AutoScroll\__history"
rmdir /Q /S "Demos\ComboTargetDemo\__history"
rmdir /Q /S "Demos\CustomFormat1\__history"
rmdir /Q /S "Demos\CustomFormat2\__history"
rmdir /Q /S "Demos\DetailedDemo\__history"
rmdir /Q /S "Demos\ExtractDemo\__history"
rmdir /Q /S "Demos\MultipleTargets\__history"
rmdir /Q /S "Demos\Outlook\__history"
rmdir /Q /S "Demos\OutlookSource\__history"
rmdir /Q /S "Demos\PIDLDemo\__history"
rmdir /Q /S "Demos\RTF\__history"
rmdir /Q /S "Demos\ShellContextMenuHandler\__history"
rmdir /Q /S "Demos\ShellContextMenuHandlerSimple\__history"
rmdir /Q /S "Demos\ShellContextMenuHandlerSimple\Win32"
rmdir /Q /S "Demos\ShellContextMenuHandlerSimple\Win64"
rmdir /Q /S "Demos\ShellDragDropHandler\__history"
rmdir /Q /S "Demos\ShellDropHandler\__history"
rmdir /Q /S "Demos\SourceAnalyzer\__history"
rmdir /Q /S "Demos\SourceDemo\__history"
rmdir /Q /S "Demos\TargetAnalyzer\__history"
rmdir /Q /S "Demos\TargetDemo\__history"
rmdir /Q /S "Demos\TreeViewTarget\__history"
rmdir /Q /S "Demos\Unicode\__history"
rmdir /Q /S "Demos\VirtualFile\__history"
rmdir /Q /S "Demos\VirtualFileStream\__history"
rmdir /Q /S "Demos\WM_DROPFILES\__history"

rmdir /Q /S "DemosWithoutInstall\Adapters\__history"
rmdir /Q /S "DemosWithoutInstall\AsyncSource\__history"
rmdir /Q /S "DemosWithoutInstall\AsyncSource with Filestreams\__history"
rmdir /Q /S "DemosWithoutInstall\AsyncTarget\__history"
rmdir /Q /S "DemosWithoutInstall\AutoScroll\__history"
rmdir /Q /S "DemosWithoutInstall\ComboTargetDemo\__history"
rmdir /Q /S "DemosWithoutInstall\CustomFormat1\__history"
rmdir /Q /S "DemosWithoutInstall\CustomFormat2\__history"
rmdir /Q /S "DemosWithoutInstall\DetailedDemo\__history"
rmdir /Q /S "DemosWithoutInstall\ExtractDemo\__history"
rmdir /Q /S "DemosWithoutInstall\MultipleTargets\__history"
rmdir /Q /S "DemosWithoutInstall\Outlook\__history"
rmdir /Q /S "DemosWithoutInstall\Outlook\__recovery"
rmdir /Q /S "DemosWithoutInstall\Outlook\Win32_Debug"
rmdir /Q /S "DemosWithoutInstall\Outlook\Win64_Debug"
rmdir /Q /S "DemosWithoutInstall\OutlookSource\__history"
rmdir /Q /S "DemosWithoutInstall\PIDLDemo\__history"
rmdir /Q /S "DemosWithoutInstall\RTF\__history"
rmdir /Q /S "DemosWithoutInstall\ShellContextMenuHandler\__history"
rmdir /Q /S "DemosWithoutInstall\ShellContextMenuHandlerSimple\__history"
rmdir /Q /S "DemosWithoutInstall\ShellContextMenuHandlerSimple\Win32"
rmdir /Q /S "DemosWithoutInstall\ShellContextMenuHandlerSimple\Win64"
rmdir /Q /S "DemosWithoutInstall\ShellDragDropHandler\__history"
rmdir /Q /S "DemosWithoutInstall\ShellDropHandler\__history"
rmdir /Q /S "DemosWithoutInstall\SourceAnalyzer\__history"
rmdir /Q /S "DemosWithoutInstall\SourceDemo\__history"
rmdir /Q /S "DemosWithoutInstall\TargetAnalyzer\__history"
rmdir /Q /S "DemosWithoutInstall\TargetDemo\__history"
rmdir /Q /S "DemosWithoutInstall\TreeViewTarget\__history"
rmdir /Q /S "DemosWithoutInstall\Unicode\__history"
rmdir /Q /S "DemosWithoutInstall\VirtualFile\__history"
rmdir /Q /S "DemosWithoutInstall\VirtualFileStream\__history"
rmdir /Q /S "DemosWithoutInstall\WM_DROPFILES\__history"
